import type { Metadata } from "next";
import "@/common/styles/globals.css";
import { Inter } from "next/font/google";
import { dir } from "i18next";
import { languages } from "@/common/i18n/settings";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export async function generateStaticParams() {
  return languages.map((lang) => ({ lang }));
}

const RootLayout: any = ({
  children,
  params: { lang },
}: {
  children: React.ReactNode;
  params: any;
}) => {
  return (
    <html lang={lang} dir={dir(lang)}>
      <body className={inter.className}>{children}</body>
    </html>
  );
};

export default RootLayout;
